### ISSUE TITLE
Add content

### ISSUE THREAD

**Issue by thefuture2092** [thefuture2092/rdc-study#13]
Ajout du contenu pour les différentes pages ajoutés.

Les pays à supporter:

- [x] Canada
- [x] Etats-Unis

Le contenu à mettre à jour:
- [x] La mission dans la page à propos (#54)
- [x] Les objectifs dans la page à propos (#54)
- [x] Les détails de chaque membre de l'équipe (#54)
- [x] La page d'accueil (#55)
- [x] Ajuster les images partagées sur les réseaux sociaux. (Page d'accueil, à propos, page de guide, etc...)
