### ISSUE TITLE
Add home page

### ISSUE THREAD

**Issue by thefuture2092** [thefuture2092/rdc-study#4]
On ajoute la page d'accueil du site Web.

- [x] Un header qui présente le nom de l'application et le motto. (#18)
- [x] Une section qui décrit le guide gratuit. (#19)
- [x] Une section qui décrit le service de vérification des dermaches. (#19)
- [x] Une section qui décrit le service d'accompagnement. (#19)
- [x] Une liste des pays supportés. (#20)
- [x] Le tout doit être responsive.

# Screenshots
![localhost_63342_rdcstudy_html5up-solid-state_index html](https://user-images.githubusercontent.com/3483656/37690631-9cc7e360-2c82-11e8-9f8b-feecad386a9e.png)

![localhost_63342_rdcstudy_html5up-solid-state_index html iphone 5_se](https://user-images.githubusercontent.com/3483656/37690632-9cd88d82-2c82-11e8-9f96-74b4bbc9884c.png)
