### ISSUE TITLE
Add contact form

### ISSUE THREAD

**Issue by thefuture2092** [thefuture2092/rdc-study#6]
- [x] Ajout du formulaire de contact à la page d'accueil. (#28)
- [x] Un email est envoyé après que l'utilisateur ait cliqué sur envoyer. (#27, #29 )
- [x] On affiche un indicateur d'activité pendant l'envoi du email. (#33)
- [x] On remplace le formulaire par un message de confirmation. (#33)
- [x] On affiche un message d'erreur en cas d'erreur de l'API. (#33)
